---
- name: Install HAProxy
  package:
    name: haproxy
    state: present

- name: Ensure HAProxy configuration directory exists
  file:
    path: /etc/haproxy
    state: directory
    owner: root
    group: root

- name: Deploy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart HAProxy

- name: Ensure HAProxy is started and enabled
  service:
    name: haproxy
    state: started
    enabled: yes