---
 # packages to be installed on all the servers
 
- name: Install common packages on all VMs
  hosts: all
  become: yes
  tasks:
    - name: Install common packages
      yum:
        name:
          - bind-utils
          - man-db # man-db is the package for man
          - man-pages
          - mlocate
          - sysstat
          - git
        state: present