---
#handler to restart ssh and reboot the system 
- name: Restart SSH
  service:
    name: sshd
    state: restarted

- name: Reboot the system
  reboot:
    reboot_timeout: 600
  when: ansible_facts.selinux.status == "enabled"
